import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Line from "../components/Line";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Line />
      <a href="https://github.com/SonnyCastro/chart.js-practice">Repo</a>
    </div>
  );
}
